/* Generated By:JJTree&JavaCC: Do not edit this line. DPLMusicCompileMagicConstants.java */
package llvm;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DPLMusicCompileMagicConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 1;
  /** RegularExpression Id. */
  int LETTER = 2;
  /** RegularExpression Id. */
  int OPEN_PAR = 3;
  /** RegularExpression Id. */
  int CLOSE_PAR = 4;
  /** RegularExpression Id. */
  int TAB = 5;
  /** RegularExpression Id. */
  int SINGLE_QOUTE = 6;
  /** RegularExpression Id. */
  int DOUBLE_QOUTE = 7;
  /** RegularExpression Id. */
  int DOUBLE_QOUTED_WORDS = 8;
  /** RegularExpression Id. */
  int EXCLAMATION = 9;
  /** RegularExpression Id. */
  int SPACE = 10;
  /** RegularExpression Id. */
  int BREAK = 11;
  /** RegularExpression Id. */
  int PAUSE = 12;
  /** RegularExpression Id. */
  int NEWLINE = 13;
  /** RegularExpression Id. */
  int WORD = 14;
  /** RegularExpression Id. */
  int SENTENCE = 15;
  /** RegularExpression Id. */
  int VERSE_START = 16;
  /** RegularExpression Id. */
  int VERSE_LINES = 17;
  /** RegularExpression Id. */
  int VERSE = 18;
  /** RegularExpression Id. */
  int BRIDGE = 19;
  /** RegularExpression Id. */
  int CHORUS = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<DIGIT>",
    "<LETTER>",
    "\"(\"",
    "\")\"",
    "\"\\t\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "<DOUBLE_QOUTED_WORDS>",
    "\"!\"",
    "\" \"",
    "\",\"",
    "\".\"",
    "<NEWLINE>",
    "<WORD>",
    "<SENTENCE>",
    "<VERSE_START>",
    "<VERSE_LINES>",
    "<VERSE>",
    "<BRIDGE>",
    "<CHORUS>",
  };

}
