/* Generated By:JavaCC: Do not edit this line. DPLMusicCompileMagicTreeConstants.java Version 5.0 */
package llvm;

public interface DPLMusicCompileMagicTreeConstants
{
  public int JJTSONG_CONSTRUCTS = 0;
  public int JJTVERSE = 1;
  public int JJTCHORUS = 2;
  public int JJTBRIDGE = 3;


  public String[] jjtNodeName = {
    "Song_Constructs",
    "VERSE",
    "CHORUS",
    "BRIDGE",
  };
}
/* JavaCC - OriginalChecksum=358bd50baa6d307b1c31dc28ce67a94e (do not edit this line) */
